# import from the compiled Rust extension module
# module-level convenience functions — mirrors httpx.{get,post,...,stream}
from ._api import (
    delete,
    get,
    head,
    options,
    patch,
    post,
    put,
    request,
    stream,
)
from ._rqx import (
    AsyncHTTPTransport,
    ConnectError,
    ConnectTimeout,
    DecodingError,
    HTTPError,
    HTTPStatusError,
    HTTPTransport,
    InvalidURL,
    JSONDecodeError,
    MaxRetriesExceeded,
    NetworkError,
    PoolTimeout,
    ProtocolError,
    ProxyError,
    PyAsyncClient,
    PyClient,
    PyHeaders,
    PyRetry,
    QueryParams,
    ReadError,
    ReadTimeout,
    RemoteProtocolError,
    RequestError,
    ResponseNotRead,
    RqxError,
    StreamClosed,
    StreamConsumed,
    StreamError,
    Timeout,
    TimeoutException,
    TooManyRedirects,
    TransportError,
    URL,
    UnsupportedProtocol,
    WriteError,
    WriteTimeout,
)

# optional: nicer names (drop Py prefix)
Client = PyClient
AsyncClient = PyAsyncClient
Headers = PyHeaders
Retry = PyRetry

__all__ = [
    "AsyncClient",
    "AsyncHTTPTransport",
    "Client",
    "ConnectError",
    "ConnectTimeout",
    "DecodingError",
    "HTTPError",
    "HTTPStatusError",
    "HTTPTransport",
    "Headers",
    "InvalidURL",
    "JSONDecodeError",
    "MaxRetriesExceeded",
    "NetworkError",
    "PoolTimeout",
    "ProtocolError",
    "ProxyError",
    "QueryParams",
    "ReadError",
    "ReadTimeout",
    "RemoteProtocolError",
    "RequestError",
    "ResponseNotRead",
    "Retry",
    "RqxError",
    "StreamClosed",
    "StreamConsumed",
    "StreamError",
    "Timeout",
    "TimeoutException",
    "TooManyRedirects",
    "TransportError",
    "URL",
    "UnsupportedProtocol",
    "WriteError",
    "WriteTimeout",
    "delete",
    "get",
    "head",
    "options",
    "patch",
    "post",
    "put",
    "request",
    "stream",
]
