"""Session fixtures. Servers and certs live in tests/fixtures/server.py."""

import ssl
import threading
import time
from http.server import HTTPServer

import pytest

from tests.fixtures.server import (
    CERTS,
    CERTS_DIR,
    FlakyServerHandler,
    MTLSHandler,
    _free_port,
    _http2_app,
    script_dir,
)


def pytest_configure(config):
    """Generate TLS certs once, before any test process can look for them.

    The certs are gitignored, so a fresh checkout (and every CI run) starts with
    an empty tests/ssl/certs/. Generating them lazily from the server fixtures
    made the timing depend on which worker happened to draw a TLS test first:
    under `-n 8`, a test reading a cert path without requesting one of those
    fixtures could run before any cert existed and fail with "failed to read
    client cert: No such file or directory" (https://github.com/rodcochran/rqx/issues/112).

    Doing it here removes the race rather than guarding it. Under xdist this
    hook runs in the controller and again in each worker, but the controller's
    call completes before xdist spawns any worker, so the `workerinput` guard
    leaves exactly one process generating within a run, and no window where a
    cert is half-written when someone reads it.

    That guard says nothing about *other* pytest runs, though, so CertSet.ensure
    still takes a file lock to serialize against a second invocation sharing the
    checkout.
    """
    if hasattr(config, "workerinput"):  # xdist sets this on workers only
        return
    CERTS.ensure()


@pytest.fixture(scope="session")
def flaky_server():
    # start server in thread
    server = HTTPServer(("localhost", 0), FlakyServerHandler)
    port = server.server_address[1]  # get the assigned port
    thread = threading.Thread(target=server.serve_forever)
    thread.daemon = True
    thread.start()
    yield f"http://localhost:{port}"
    server.shutdown()


@pytest.fixture(scope="session")
def http2_server():
    """Local HTTPS server speaking both HTTP/2 and HTTP/1.1 via ALPN.

    Replaces nghttp2.org/httpbin/ for HTTP version-negotiation coverage.
    Returns a base URL like https://localhost:PORT. The TLS cert is the
    self-signed cert generated by tests/ssl/generate_certs.sh, so callers
    should pass `verify=False` (or point verify= at tests/ssl/certs/ca-cert.pem).
    """
    import asyncio

    from hypercorn.asyncio import serve
    from hypercorn.config import Config

    port = _free_port()
    config = Config()
    config.bind = [f"127.0.0.1:{port}"]
    config.certfile = str(CERTS_DIR / "server-cert.pem")
    config.keyfile = str(CERTS_DIR / "server-key.pem")
    # ALPN: advertise h2 first, then http/1.1. Clients that propose either
    # will negotiate to their preferred version.
    config.alpn_protocols = ["h2", "http/1.1"]
    # Hypercorn logs every request by default; silence for clean test output.
    config.accesslog = None
    config.errorlog = None

    shutdown = threading.Event()

    async def _shutdown_trigger():
        # Polls the threading.Event so the asyncio loop can react to a
        # cross-thread shutdown signal without blocking.
        while not shutdown.is_set():
            await asyncio.sleep(0.05)

    def _run():
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        try:
            loop.run_until_complete(
                serve(_http2_app, config, shutdown_trigger=_shutdown_trigger)
            )
        finally:
            loop.close()

    thread = threading.Thread(target=_run, daemon=True)
    thread.start()

    # Wait for the port to accept connections before yielding — otherwise the
    # first test races the server startup.
    import socket as _socket

    deadline = time.time() + 5.0
    while time.time() < deadline:
        try:
            with _socket.create_connection(("127.0.0.1", port), timeout=0.5):
                break
        except OSError:
            time.sleep(0.05)
    else:
        shutdown.set()
        raise RuntimeError(f"http2_server didn't come up on port {port}")

    try:
        yield f"https://localhost:{port}"
    finally:
        shutdown.set()
        thread.join(timeout=5.0)


@pytest.fixture(scope="session")
def mtls_server():
    # Certs are generated up front in pytest_configure.
    ssl_context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
    ssl_context.load_cert_chain(
        certfile=f"{script_dir}/ssl/certs/server-cert.pem",
        keyfile=f"{script_dir}/ssl/certs/server-key.pem",
    )

    # whose-signed-clients-do-I-trust
    ssl_context.load_verify_locations(cafile=f"{script_dir}/ssl/certs/ca-cert.pem")

    # actually demand a client cert
    ssl_context.verify_mode = ssl.CERT_REQUIRED

    server = HTTPServer(("localhost", 0), MTLSHandler)
    server.socket = ssl_context.wrap_socket(server.socket, server_side=True)
    port = server.server_address[1]  # get the assigned port
    thread = threading.Thread(target=server.serve_forever)
    thread.daemon = True
    thread.start()
    yield f"https://localhost:{port}"
    server.shutdown()
