services:
  nginx:
    image: nginx:alpine
    ports:
      - '8080:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/response.json:/usr/share/nginx/html/response.json
      - ./nginx/response-10kb.json:/usr/share/nginx/html/response-10kb.json
      - ./nginx/response-100kb.json:/usr/share/nginx/html/response-100kb.json
